### ISSUE TITLE
renderToStaticMarkup is not allowed in Next.js 14

### ISSUE THREAD

**Issue by cooperlang** [EvHaus/react-pdf-charts#151] opened 2023-11-19 00:06 UTC
### Describe the bug

Even though the React 18 documentation indicates that there is still limited support for renderToStaticMarkup, Next.js 14 does not recognize it as valid for use.

This is the error produced when using react-pdf-charts in Next.js 14

Uncaught Error: Internal Error: do not use legacy react-dom/server APIs. If you encountered this error, please open an issue on the Next.js repo.
    at renderToStaticMarkup (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/build/noop-react-dom-server-legacy.js:25:11)
    at webSvgToPdfSvg (webpack-internal:///(:3000/app-pages-browser)/./node_modules/react-pdf-charts/dist/index.js:166:91)
    at ReactPDFChart (webpack-internal:///(:3000/app-pages-browser)/./node_modules/react-pdf-charts/dist/index.js:370:21)
    at Jd (webpack-internal:///(:3000/app-pages-browser)/./node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js:1173:9)
    at ig (webpack-internal:///(:3000/app-pages-browser)/./node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js:3422:13)
    at hg (webpack-internal:///(:3000/app-pages-browser)/./node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js:2889:13)
    at bg (webpack-internal:///(:3000/app-pages-browser)/./node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js:2883:29)
    at Of (webpack-internal:///(:3000/app-pages-browser)/./node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js:2685:11)
    at eval (webpack-internal:///(:3000/app-pages-browser)/./node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js:532:20)
    at unstable_runWithPriority (webpack-internal:///(:3000/app-pages-browser)/./node_modules/@react-pdf/renderer/node_modules/scheduler/cjs/scheduler.development.js:818:12)
    at hc (webpack-internal:///(:3000/app-pages-browser)/./node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js:505:12)
    at kc (webpack-internal:///(:3000/app-pages-browser)/./node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js:529:9)
    at F (webpack-internal:///(:3000/app-pages-browser)/./node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js:521:5)
    at Wc (webpack-internal:///(:3000/app-pages-browser)/./node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js:2521:93)
    at Object.updateContainer (webpack-internal:///(:3000/app-pages-browser)/./node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js:3807:7)
    at Object.updateContainer (webpack-internal:///(:3000/app-pages-browser)/./node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js:4129:14)
    at eval (webpack-internal:///(:3000/app-pages-browser)/./node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js:4382:25)
    at eval (webpack-internal:///(:3000/app-pages-browser)/./node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js:4443:12)
    at commitHookEffectListMount (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:20995:23)
    at commitHookPassiveMountEffects (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23048:7)
    at commitPassiveMountOnFiber (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23153:11)
    at recursivelyTraversePassiveMountEffects (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23131:7)
    at commitPassiveMountOnFiber (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23150:9)
    at recursivelyTraversePassiveMountEffects (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23131:7)
    at commitPassiveMountOnFiber (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23150:9)
    at recursivelyTraversePassiveMountEffects (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23131:7)
    at commitPassiveMountOnFiber (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23264:9)
    at recursivelyTraversePassiveMountEffects (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23131:7)
    at commitPassiveMountOnFiber (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23264:9)
    at recursivelyTraversePassiveMountEffects (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23131:7)
    at commitPassiveMountOnFiber (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23264:9)
    at recursivelyTraversePassiveMountEffects (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23131:7)
    at commitPassiveMountOnFiber (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23150:9)
    at recursivelyTraversePassiveMountEffects (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23131:7)
    at commitPassiveMountOnFiber (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23264:9)
    at recursivelyTraversePassiveMountEffects (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23131:7)
    at commitPassiveMountOnFiber (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23150:9)
    at recursivelyTraversePassiveMountEffects (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23131:7)
    at commitPassiveMountOnFiber (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23150:9)
    at recursivelyTraversePassiveMountEffects (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23131:7)
    at commitPassiveMountOnFiber (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23150:9)
    at recursivelyTraversePassiveMountEffects (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23131:7)
    at commitPassiveMountOnFiber (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23150:9)
    at recursivelyTraversePassiveMountEffects (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23131:7)
    at commitPassiveMountOnFiber (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23264:9)
    at recursivelyTraversePassiveMountEffects (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23131:7)
    at commitPassiveMountOnFiber (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23150:9)
    at recursivelyTraversePassiveMountEffects (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23131:7)
    at commitPassiveMountOnFiber (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23150:9)
    at recursivelyTraversePassiveMountEffects (webpack-internal:///(:3000/app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23131:7)

### Reproduction

Load up the most basic implementation of react-pdf-charts and using recharts to create my chart components. This immediately prevents the page containing my charts from loading and produces the above error in the console.

This error only occurs when implementing it in "next": "14.0.2", earlier versions of Next do not have this issue as far as I can tell.

<ReactPDFChart>
      <BarChart
        width={500}
        height={300}
        data={props.data}
        margin={{
          top: 5,
          right: 30,
          left: 20,
          bottom: 5,
        }}
      >
        <CartesianGrid strokeDasharray="3 3" />
        <XAxis dataKey="name" width={120} />
        <YAxis>
          <Label
            style={{
              textAnchor: 'middle',
              fontSize: '150%',
              fill: 'black',
            }}
            angle={270}
            // dy={-10}
            value={translatedYaxisLabel}
            // content={<CustomizedYAxisLabel content={translatedYaxisLabel} />}
            position={'insideLeft'}
          />
        </YAxis>

        <Bar
          isAnimationActive={false}
          dataKey="value"
          barSize={120}
          radius={[5, 5, 0, 0]}
          stroke="black"
          strokeWidth={2}
          label={{ position: 'top' }}
        >
          {data.map((entry, index) => (
            <Cell
              key={`cell-${index}`}
              fill={brandColors[index % brandColors.length]}
            />
          ))}
        </Bar>
      </BarChart>
    </ReactPDFChart>

### Validations

- [X] Check that there isn't [already an issue](https://github.com/EvHaus/react-pdf-charts/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that you're confident that this is a legitimate bug. To ask a question open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by EvHaus** [comment] 2023-11-19 00:42
Possibly a duplicate of #109

**Comment by EvHaus** [comment] 2023-11-19 03:59
As the error says:
> Uncaught Error: Internal Error: do not use legacy react-dom/server APIs. If you encountered this error, please open an issue on the Next.js repo.

I would recommend opening this as a bug with the Next.js team. They should support the React APIs properly.

**Comment by nextrie** [comment] 2024-01-31 23:58
same problem here, had to downgrade to next^13.X

**Comment by EvHaus** [comment] 2024-02-01 06:34
Hey all. I think I have a working solution for Next 14 for client side rendering. There's a few things you need to do:

1. To get around [this bug](https://github.com/diegomura/react-pdf/issues/2574) in the latest version of `react-pdf` you need to add this to you `package.json`:
```
"overrides": {
  "@react-pdf/image": "2.2.3",
  "@react-pdf/pdfkit": "3.0.4"
}
```
2. To ensure `react-pdf` loads on Next 13+ you'll also need this ([as per](https://github.com/diegomura/react-pdf/issues/2350#issuecomment-1914234934)) in your `next.config.js`:
```
experimental: {
  serverComponentsExternalPackages: ['@react-pdf/renderer']
}
```
3. And finally, to render `react-pdf` components on the client and use `<PDFViewer />` without getting  `Error: PDFViewer is a web specific API.` errors you'll need to use `next/dynamic` to load your PDF components.

When you put it all together -- it works. Here's a working PDF chart rendered on the client using Next 14.1.0: https://stackblitz.com/edit/stackblitz-starters-aux53n?file=app%2FMyDocument.tsx

![image](https://github.com/EvHaus/react-pdf-charts/assets/226640/47399a55-5619-4803-822f-299a038aebbe)

I'll close this issue for now. If you're still running into other problems, feel free to leave another comment with a repro of what you're seeing.

**Closed by EvHaus** 2024-02-01 06:34 UTC
Labels: bug, help wanted

**Comment by cooperlang** [comment] 2024-02-01 17:31
Brilliant! Thank you for looking into this.
