### ISSUE TITLE
Minified React error 130 on clean install

### ISSUE THREAD

**Issue by kylekz** [EvHaus/react-pdf-charts#493] opened 2024-10-25 02:27 UTC
### Describe the bug

In my real project, I'm using recharts. Using that here, I get an error such as:
`TypeError: Super expression must either be null or a function`
stacktrace: https://gist.github.com/kylekz/fee1939cbe9f0fc7c9a0a48ebf316b0e

So I figured I'd try using victory just for the PDF part. This results in this error:
` Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`
stacktrace: https://gist.github.com/kylekz/fc58fea742384aacfffa4d8b58c23649

I'm unable to make a minimal reproduction for the recharts error. What I am able to reproduce, is the victory error, which happens for both recharts and victory here. For whatever reason, I get minified React errors in the repro, but the error matches what I'm getting anyway:
`Error: Minified React error #130;`
stacktrace: https://gist.github.com/kylekz/3fa91d77902e1bb8f6565cdfe7b2ad7b

I've tried varying versions of `@react-pdf/renderer`: 3.2.1, 3.4.4, 4.0.0 and all result in the same thing. Perhaps I'm just doing something wrong or too complex and just need to bail out to html2canvas or html2image.

### Reproduction

https://github.com/kylekz/pdf-charts-repro

1. create a new nextjs app using 14.2.15
2. install dependencies: `@react-pdf/renderer`, `recharts`, `victory`, `react-pdf-charts`
3. create routes rendering to buffer and returning the response, using minimal examples from either chart lib
4. see error

### Validations

- [X] Check that there isn't [already an issue](https://github.com/EvHaus/react-pdf-charts/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that you're confident that this is a legitimate bug. To ask a question open a [GitHub Discussion](https://github.com/EvHaus/react-pdf-charts/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by EvHaus** [comment] 2024-10-25 04:06
Thanks for the excellent repro steps and details.

You can get past the ` Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.` error by removing `use client` from your `component.tsx` file. But that will not fix the `TypeError: Super expression must either be null or a function` error.

Unfortunately your issue is a duplicate of https://github.com/EvHaus/react-pdf-charts/issues/109#issuecomment-192063712. Next.js App router simply does not handle something inside `recharts` being executed within their limited RSC environment.

I'm currently using `react-pdf-charts` in a production app using Next.js, but using the `/api` folder of the Pages router. In that environment is works just fine. Sorry, I haven't yet found any way to fix it for the App Router.

I'm going to close this issue for now to keep the discussion centralized in #109, but feel free to add additional comments here if you ever figure out a way to move forward here.

**Closed by EvHaus** 2024-10-25 04:06 UTC
Labels: bug
